# did.dyne.org domain_name=did.dyne.org ansible_port=22060 ansible_python_interpreter=/usr/bin/python3
116.203.198.188 domain_name=127.0.0.1 ansible_python_interpreter=/usr/bin/python3 ansible_port=22010
