---
- name: start controller
  hosts: all
  remote_user: root
  become_user: controller
  become_method: su
  vars:
    controller_root: "/controller"
  tasks:
  - name: Delete old logs
    file:
      path: "/home/controller/.pm2/logs/"
      state: absent

  - name: Create PM2 startup script
    become: false
    command: env PATH=$PATH:/usr/bin pm2 startup systemd -u controller --hp /home/controller
    args:
      chdir: "{{ controller_root }}"

  - name: Start services
    command: pm2 start ecosystem.config.js
    args:
      chdir: "{{ controller_root }}"

  - name: Save pm2 configuration
    command: pm2 save
    args:
      chdir: "{{ controller_root }}"

  - name: Restart nginx
    become: false
    service: name=nginx state=restarted enabled=true
