name: 🚀 Deploy did explorer
on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    uses: dyne/workflows/.github/workflows/node-staging-deploy.yml@main
    secrets: inherit
    with:
      deploy_url: https://explorer.did.dyne.org
