name: W3C-DID CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  restroom-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version: [14.18.0, 16.13.0]
    defaults:
      run:
        working-directory: restroom

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn ava
