name: W3C-DID CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  restroom_job:
    runs-on: ubuntu-latest
    name: Start restroom and request a simple contract
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Start restroom
        uses: dyne/restroom-github-action
        with:
          restroom-contracts: "${{ github.workspace }}/contracts"
      - name: Install curl
        run: sudo apt install curl
      - name: Run tests
        run: ./test/run.sh
