name: W3C-DID CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-units:
    runs-on: ubuntu-latest
    name: 🧪 test-units
    steps:
      - uses: actions/checkout@v3
      - name: install Zenroom
        run: |
          sudo apt install wget
          wget https://github.com/dyne/zenroom/releases/latest/download/zenroom -O zenroom
          chmod +x zenroom
          cp zenroom test/
      - name: tests
        run: |
          make test-units

  restroom_job:
    runs-on: ubuntu-latest
    name: 🧪 restroom tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt install curl wget jq
      - name: install Zenroom
        run: |
          wget https://github.com/dyne/zenroom/releases/latest/download/zenroom -O zenroom
          chmod +x zenroom
      - name: Start restroom
        uses: dyne/restroom-github-action@v1
        with:
          restroom-contracts: "${{ github.workspace }}/contracts"
          restroom-files: "${{ github.workspace }}/"
      - name: Run tests
        run: ./test/run.sh
